// flow-typed signature: 6371adb16643f74f201f76609977b46d
// flow-typed version: <<STUB>>/eslint-plugin-flowtype-errors_v^3.6.0/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-flowtype-errors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-flowtype-errors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-flowtype-errors/dist/collect' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flowtype-errors/dist/format' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flowtype-errors/dist/get-program' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flowtype-errors/dist' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flowtype-errors/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-flowtype-errors/dist/collect.js' {
  declare module.exports: $Exports<'eslint-plugin-flowtype-errors/dist/collect'>;
}
declare module 'eslint-plugin-flowtype-errors/dist/format.js' {
  declare module.exports: $Exports<'eslint-plugin-flowtype-errors/dist/format'>;
}
declare module 'eslint-plugin-flowtype-errors/dist/get-program.js' {
  declare module.exports: $Exports<'eslint-plugin-flowtype-errors/dist/get-program'>;
}
declare module 'eslint-plugin-flowtype-errors/dist/index' {
  declare module.exports: $Exports<'eslint-plugin-flowtype-errors/dist'>;
}
declare module 'eslint-plugin-flowtype-errors/dist/index.js' {
  declare module.exports: $Exports<'eslint-plugin-flowtype-errors/dist'>;
}
declare module 'eslint-plugin-flowtype-errors/index' {
  declare module.exports: $Exports<'eslint-plugin-flowtype-errors'>;
}
declare module 'eslint-plugin-flowtype-errors/index.js' {
  declare module.exports: $Exports<'eslint-plugin-flowtype-errors'>;
}
declare module 'eslint-plugin-flowtype-errors/src/index' {
  declare module.exports: $Exports<'eslint-plugin-flowtype-errors/src'>;
}
declare module 'eslint-plugin-flowtype-errors/src/index.js' {
  declare module.exports: $Exports<'eslint-plugin-flowtype-errors/src'>;
}
