// flow-typed signature: d6d3fd622fb5034d5c14e23d5fc152e4
// flow-typed version: <<STUB>>/normalize.css_v^8.0.0/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
